### ISSUE TITLE
FTP error: [Errno 2] No such file or directory: '/test_input/test_fastq_R1.fastq'

### ISSUE THREAD

**Issue by DOH-KEW4303** [CDCgov/seqsender#1]
I am getting this error when I try to run the test submit command:
`python seqsender.py submit --unique_name test_submission --config test_config.yaml --metadata /root/miniconda3/seqsender/test_input/test_metadata.tsv  --fasta /root/miniconda3/seqsender/test_input/test_fasta.fasta --test`

The output first says:
Processing test_submission.
Processing Files.
Creating GISAID files.
Creating Genbank files.
Creating BioSample files.
Creating SRA files.
test_submission complete.

Submission report exists pulling down.
Submitting to SRA/BioSample.

Followed by the FTP error described above. Does anything appear to be missing? Thank you

**Comment by DOH-KEW4303** [comment]
Issue resolved. I looked  over the TOAST presentation recording and saw in the config file I needed to change submit_SRA to False. However I have just tried to run the final command in the test instructions:
`python seqsender.py update_submissions`

And the output shows:
Updating: test_submission BioSample
Report exists pulling down
Status: processed-error

What would be causing the error at this stage? Thank you

**Comment by leebrian** [comment]
@dthoward96  said this is completed and solved and assigning to help with documenting and closing out.

**Comment by dthoward96** [comment]
When submitting to the test server if you overwrite the submission multiple with the same submission name or are missing required metadata for that submission it can give you the "processed-error" flag. To better understand the issue you can look inside the report.xml generated in the biosample_sra folder which will better explain the issue. You can also try submitting under a new unique_name and removing the previous submission from the log in order to send it as a fresh submission as it could be still expecting SRA related information if that was enabled in the original submission.
